[package]
name = "rulescript"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = "*"
smtlib = "*"
thiserror = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
reedline = "*"
tokio = { version = "*", features = ["rt", "rt-multi-thread", "macros"] }
